config/routes.rb
StarterApp::Application.routes.draw do
  root 'projects#index'
  resources :projects

  resources :users

  resources :stories do
    resources :comments, only: [:create, :destroy]
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :story	
  validates :story, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
   validates_uniqueness_of :name

   has_many :stories #, dependent: :destroy -TODO
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :comments

  VALID_STATUSES = ['ice box', 'ready', 'started', 'done']
  VALID_ESTIMATES = (1..5).to_a

  validates :stakeholder, :goal, :behavior, :project, presence: true
  validates_length_of :tag, :maximum => 40
  
  scope :bv_ascending, -> { order("business_value ASC")}
  scope :bv_descending, -> { order("business_value DESC")}
  belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # POST /stories/comments
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to @comment.story, notice: 'Comment was successfully created.'
    else
      #render action: 'new'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :story_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  def index
    @stories = Story.bv_descending
  end

  # GET /stories/1
  def show
    @comment = Comment.new(story_id: @story.id)
  end

  # GET /stories/new
  def new
    @story = Story.new
    @projects = Project.all
  end

  # GET /stories/1/edit
  def edit
    @projects = Project.all
  end

  # POST /stories
  def create
    @story = Story.new(story_params)
    @projects = Project.all

    if @story.save
      redirect_to @story, notice: 'Story was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /stories/1
  def update
    if @story.update(story_params)
      redirect_to @story, notice: 'Story was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /stories/1
  def destroy
    @story.destroy
    redirect_to stories_url, notice: 'Story was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id], include: :comments)
    end

    # Only allow a trusted parameter "white list" through.
    def story_params
      params.require(:story).permit(:goal, :stakeholder, :behavior, :business_value, :complexity_value, :tag, :assignee, :project_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:username, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <%= comment.body %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@story, @comment]) do |f| %>
<% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

  <%= f.hidden_field :story_id %>

<div class="field">
  <%= f.label :body %><br>
  <%= f.text_field :body %>
</div>
<div class="actions">
  <%= f.submit "Submit" %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>
<div class="project-list">
  <% @projects.each do |project| %>
    <div class="project row">
      <div class="project-name small-8 columns">
        <div class="row" title="business value">
          <%= link_to project.name, edit_project_path(project) %>
        </div>
      </div>
      <div class="small-4 columns">
        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>             
    </div>
  <% end %>
</div>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="large-8 columns">

      <div class="row">
        <div class="large-2 columns">
          <%= f.label :project_id, "Project"%>
        </div>
        <div class="large-10 columns">
          <%= f.select :project_id, options_from_collection_for_select(@projects, 'id', 'name')  %>
        </div>
      </div>

      <div class="row">
        <div class="large-2 columns">
          <%= f.label :goal, "In order to", class: "inline" %>
        </div>
        <div class="large-10 columns">
          <%= f.text_field :goal %>
        </div>
      </div>

      <div class="row">
        <div class="large-2 columns">
          <%= f.label :stakeholder, "As a", class: "inline" %>
        </div>
        <div class="large-10 columns">
          <%= f.text_field :stakeholder %>
        </div>
      </div>

      <div class="row">
        <div class="large-2 columns">
          <%= f.label :behavior, "I want to", class: "inline" %>
        </div>
        <div class="large-10 columns">
          <%= f.text_field :behavior %>
        </div>
      </div>

      <div class="row">
        <div class="large-2 columns">
          <%= f.label :tag, class: "inline" %>
        </div>
        <div class="large-10 columns">
          <%= f.text_field :tag %>
        </div>
      </div>

      <div class="row">
        <div class="large-2 columns">
          <%= f.label :assignee, class: "inline" %>
        </div>
        <div class="large-10 columns">
          <%= f.text_field :assignee %>
        </div >
      </div>

      <div class="row">
        <div class="large-2 columns">
          <%= f.label :status, class: "inline" %>
        </div>
        <div class="large-10 columns">
          <%= f.select :status, Story::VALID_STATUSES %>
        </div>
      </div>

      <div class="row">
        <div class="large-10 columns offset-large-2">
          <div class="actions">
            <%= f.submit "Save Story" %>
          </div>
        </div>
      </div>
    </div>
    <div class="large-4 columns">
      <div class="row">
        <div class="large-6 columns">
          <%= f.label :business_value %>
          <%= f.select :business_value, Story::VALID_ESTIMATES %>
        </div>

        <div class="large-6 columns">
          <%= f.label :complexity_value %>
          <%= f.select :complexity_value, Story::VALID_ESTIMATES %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<div class="story-list">
  <% @stories.each do |story| %>
    <div class="story row">
      <div class="story-estimations small-1 columns">
        <div class="row" title="business value">
          <%= story.business_value %>
        </div>
        <div class="row" title="complexity value">
          <%= story.complexity_value %>
        </div>
      </div>
      <div class="story-details small-10 columns">
        <div class="story-details--behavior">
          <%= link_to story.behavior , edit_story_path(story) %>
        </div>
        <div class="story-details--status">
          <%= story.status %>
        </div>
      </div>
      <div class="small-1 columns">
        <%#= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      
    </div>  
  <% end %>
</div>

<br>
<%= link_to "Sort the Stories",stories_path%><br>
<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @story.project.name %>
</p>

<p>
  <strong>Goal:</strong>
  <%= @story.goal %>
</p>

<p>
  <strong>Stakeholder:</strong>
  <%= @story.stakeholder %>
</p>

<p>
  <strong>Behavior:</strong>
  <%= @story.behavior %>
</p>

<p>
  <strong>Business value:</strong>
  <%= @story.business_value %>
</p>

<p>
  <strong>Complexity value:</strong>
  <%= @story.complexity_value %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @story.tag %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @story.assignee %>
</p>

<button type="button">Add Comment</button>
<%= render :partial => "comments/form" %>
<%= render @story.comments %>

<%= link_to 'Edit', edit_story_path(@story) %>
<%= link_to 'Back', stories_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>